root: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

env:
  es2023: true
  node: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  project:
    - tsconfig.json
    - tsconfig.node.json

settings:
  import/resolver: typescript

rules:
  '@typescript-eslint/no-var-requires': off
  import/extensions: off
  import/order:
    - warn
    - newlines-between: always
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '*.ts'
  import/prefer-default-export: off
  no-console: off

overrides:
  - files: ['client']

    extends:
      - airbnb
      - airbnb-typescript
      - airbnb/hooks
      - plugin:react/jsx-runtime

    env:
      node: false
      browser: true

    plugins:
      - simple-import-sort

    rules:
      import/order: off
      jsx-a11y/label-has-associated-control:
        - error
        - assert: either
      react/function-component-definition:
        - error
        - namedComponents: arrow-function
          unnamedComponents: arrow-function
      react/jsx-props-no-spreading: off
      react/jsx-sort-props:
        - warn
        - ignoreCase: true
          callbacksLast: true
          shorthandLast: true
          reservedFirst: true
      react/require-default-props:
        - error
        - functions: defaultArguments
      react/prop-types: off
      simple-import-sort/exports: warn
      simple-import-sort/imports: warn
      sort-imports: off
